# Generated by Django 4.2.11 on 2026-03-07 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='taux_tva',
            new_name='tva_rate',
        ),
        migrations.AddField(
            model_name='facture',
            name='subtotal_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sous-total HT'),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total TTC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='item_type',
            field=models.CharField(choices=[('NORMAL', 'Ligne'), ('DEBOURS', 'Débours')], default='NORMAL', max_length=20, verbose_name='Type de ligne'),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.CharField(blank=True, max_length=20, verbose_name='RC'),
        ),
    ]
